name: CPU Tests

on:
  push:
    branches:
      - main

jobs:
  do-the-job:
    name: Do the job on the cpu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - {os: ubuntu-latest, architecture: x64, python-version: '3.10'}
          - {os: ubuntu-latest, architecture: x64, python-version: '3.11'}
          - {os: macos-latest, architecture: arm64, python-version: '3.10'}
          - {os: macos-latest, architecture: arm64, python-version: '3.11'}
    steps:
      - name: Hello World
        run: echo 'Hello World!'
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipx and ensure it's up to date
        run: |
          python -m pip install --upgrade pipx
          pipx ensurepath
        shell: bash
      - name: Install poetry
        run: pipx install poetry
        shell: bash
      - name: Install dependencies with Poetry
        run: |
          poetry run pip install pytest torch
        shell: bash
      - name: Run unit tests
        run: poetry run pytest
