name: CPU Tests

on:
  push:
    branches:
      - main

jobs:
  do-the-job:
    name: Do the job on the cpu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          # - {os: ubuntu-latest, architecture: x64, python-version: '3.10'}
          # - {os: ubuntu-latest, architecture: x64, python-version: '3.11'}
          - {os: macos-latest, architecture: arm64, python-version: '3.10'}
          - {os: macos-latest, architecture: arm64, python-version: '3.11'}
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction
        shell: bash
      - name: Run unit tests
        run: poetry run pytest
