name: GPU Tests

on:
  workflow_run:
    workflows: ["CPU Tests"]  # Replace with the exact name of the CPU tests workflow
    types:
      - completed

jobs:
  start-runner:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Trigger only if CPU tests succeed
    name: Start self-hosted EC2 runner for GPU
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_TOKEN }}
          ec2-image-id: ${{ vars.AWS_IMAGE_ID }}
          ec2-instance-type: ${{ vars.AWS_INSTANCE_TYPE }}
          subnet-id: ${{ vars.AWS_SUBNET }}
          security-group-id: ${{ vars.AWS_SECURITY_GROUP }}
          runner-home-dir: /dev/shm

  do-the-job:
    name: Run GPU Tests on the runner
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 1
      - name: Change Poetry cache folder
        run: |
          export POETRY_CACHE_DIR=/dev/shm/
          echo "Poetry cache folder changed to: $POETRY_CACHE_DIR"
      - name: Change Python cache folder
        run: |
          export PYTHON_CACHE_DIR=/dev/shm/
          export AGENT_TOOLSDIRECTORY=/dev/shm/
          echo "Python cache folder changed to: $PYTHON_CACHE_DIR"
          echo "Agent Tools folder changed to: $AGENT_TOOLSDIRECTORY"
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: /dev/shm/
      - name: Check space
        run: |
          echo "available space: "
          df -h
      - name: Check poetry version
        run: |
          poetry env info
          poetry --version
      - name: Install dependencies with Poetry
        run: |
          poetry install
        shell: bash
      - name: Run unit tests
        run: poetry run pytest
        shell: bash

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # waits for the EC2 instance to be created
      - do-the-job # waits for the actual job to finish
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if an error occurred in previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
